services:
  user-service:
    # Anonymous volume
    volumes:
      - ./user-service:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm ci --include=dev && exec npm run dev"]