services:
  user-service-node-app:
    ports:
      - "4949:3000"
    volumes:
      - ./user-service/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev